resources:
- name: ggrlab_concourse
  type: git
  icon: github
  source:
    branch: main
    uri: https://github.com/ggrlab/concourse
    # uri: git@github.com:ggrlab/concourse.git

jobs:
  - name: configure-self
    plan:
    - get: ggrlab_concourse
      trigger: true
    - set_pipeline: parent-pipelines
      file: ggrlab_concourse/pipelines/parent-pipelines.yml
  - name: configure-pipelines
    public: true
    plan:
      - get: ggrlab_concourse
        trigger: true
        passed: [configure-self]

# fly -t ccc destroy-pipeline -p parent-pipelines
# fly -t ccc destroy-pipeline -p hello-world
# fly -t ccc destroy-pipeline -p hello-world-2

# fly -t ccc set-pipeline -p parent-pipelines -c pipelines/parent-pipelines.yml
# fly -t ccc unpause-pipeline -p parent-pipelines
# fly -t ccc trigger-job -j parent-pipelines/configure-pipelines --watch
# fly -t ccc check-resource --resource parent-pipelines/ggrlab_concourse